/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 53
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_SEMI = 2,
  anon_sym_PIPE = 3,
  anon_sym_COMMA = 4,
  anon_sym_DASH = 5,
  anon_sym_STAR = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_LPAREN_SLASH = 9,
  anon_sym_SLASH_RPAREN = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_LPAREN_COLON = 13,
  anon_sym_COLON_RPAREN = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_QMARK = 17,
  aux_sym_special_sequence_token1 = 18,
  sym_empty_sequence = 19,
  sym_meta_identifier = 20,
  anon_sym_SQUOTE = 21,
  aux_sym_terminal_string_token1 = 22,
  anon_sym_DQUOTE = 23,
  aux_sym_terminal_string_token2 = 24,
  sym_integer = 25,
  anon_sym_LPAREN_STAR = 26,
  aux_sym_comment_token1 = 27,
  sym_source_file = 28,
  sym_syntax_rule = 29,
  sym_definitions_list = 30,
  sym_single_definition = 31,
  sym_syntactic_term = 32,
  sym_syntactic_factor = 33,
  sym_syntactic_primary = 34,
  sym_optional_sequence = 35,
  sym_repeated_sequence = 36,
  sym_grouped_sequence = 37,
  sym_special_sequence = 38,
  sym_terminal_string = 39,
  sym_comment = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_definitions_list_repeat1 = 42,
  aux_sym_single_definition_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_PIPE] = "|",
  [anon_sym_COMMA] = ",",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN_SLASH] = "(/",
  [anon_sym_SLASH_RPAREN] = "/)",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN_COLON] = "(:",
  [anon_sym_COLON_RPAREN] = ":)",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_QMARK] = "\?",
  [aux_sym_special_sequence_token1] = "special_sequence_token1",
  [sym_empty_sequence] = "empty_sequence",
  [sym_meta_identifier] = "meta_identifier",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_terminal_string_token1] = "terminal_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_terminal_string_token2] = "terminal_string_token2",
  [sym_integer] = "integer",
  [anon_sym_LPAREN_STAR] = "(*",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym_syntax_rule] = "syntax_rule",
  [sym_definitions_list] = "definitions_list",
  [sym_single_definition] = "single_definition",
  [sym_syntactic_term] = "syntactic_term",
  [sym_syntactic_factor] = "syntactic_factor",
  [sym_syntactic_primary] = "syntactic_primary",
  [sym_optional_sequence] = "optional_sequence",
  [sym_repeated_sequence] = "repeated_sequence",
  [sym_grouped_sequence] = "grouped_sequence",
  [sym_special_sequence] = "special_sequence",
  [sym_terminal_string] = "terminal_string",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_definitions_list_repeat1] = "definitions_list_repeat1",
  [aux_sym_single_definition_repeat1] = "single_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN_SLASH] = anon_sym_LPAREN_SLASH,
  [anon_sym_SLASH_RPAREN] = anon_sym_SLASH_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN_COLON] = anon_sym_LPAREN_COLON,
  [anon_sym_COLON_RPAREN] = anon_sym_COLON_RPAREN,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [aux_sym_special_sequence_token1] = aux_sym_special_sequence_token1,
  [sym_empty_sequence] = sym_empty_sequence,
  [sym_meta_identifier] = sym_meta_identifier,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_terminal_string_token1] = aux_sym_terminal_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_terminal_string_token2] = aux_sym_terminal_string_token2,
  [sym_integer] = sym_integer,
  [anon_sym_LPAREN_STAR] = anon_sym_LPAREN_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_syntax_rule] = sym_syntax_rule,
  [sym_definitions_list] = sym_definitions_list,
  [sym_single_definition] = sym_single_definition,
  [sym_syntactic_term] = sym_syntactic_term,
  [sym_syntactic_factor] = sym_syntactic_factor,
  [sym_syntactic_primary] = sym_syntactic_primary,
  [sym_optional_sequence] = sym_optional_sequence,
  [sym_repeated_sequence] = sym_repeated_sequence,
  [sym_grouped_sequence] = sym_grouped_sequence,
  [sym_special_sequence] = sym_special_sequence,
  [sym_terminal_string] = sym_terminal_string,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_definitions_list_repeat1] = aux_sym_definitions_list_repeat1,
  [aux_sym_single_definition_repeat1] = aux_sym_single_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_special_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_empty_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_meta_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_terminal_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_terminal_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_syntax_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_definitions_list] = {
    .visible = true,
    .named = true,
  },
  [sym_single_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_syntactic_term] = {
    .visible = true,
    .named = true,
  },
  [sym_syntactic_factor] = {
    .visible = true,
    .named = true,
  },
  [sym_syntactic_primary] = {
    .visible = true,
    .named = true,
  },
  [sym_optional_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_repeated_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_special_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_definitions_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 33,
        '\'', 29,
        '(', 21,
        ')', 22,
        '*', 12,
        ',', 10,
        '-', 11,
        '/', 2,
        ':', 3,
        ';', 8,
        '=', 7,
        '?', 23,
        '[', 13,
        ']', 14,
        '{', 17,
        '|', 9,
        '}', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == '*') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(39);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN_SLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH_RPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COLON_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == ':') ADVANCE(19);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_special_sequence_token1);
      if (lookahead == '(') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '?') ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_special_sequence_token1);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '?') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_special_sequence_token1);
      if (lookahead != 0 &&
          lookahead != '?') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_empty_sequence);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_meta_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_terminal_string_token1);
      if (lookahead == '(') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '(') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_terminal_string_token1);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_terminal_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_terminal_string_token2);
      if (lookahead == '(') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_terminal_string_token2);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_terminal_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '*') ADVANCE(4);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(36);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(32);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      if (lookahead != 0 &&
          lookahead != '?') ADVANCE(26);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '*') ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 24},
  [39] = {.lex_state = 34},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 30},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN_COLON] = ACTIONS(1),
    [anon_sym_COLON_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [sym_empty_sequence] = ACTIONS(1),
    [sym_meta_identifier] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(49),
    [sym_syntax_rule] = STATE(33),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_meta_identifier] = ACTIONS(7),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_definitions_list] = STATE(37),
    [sym_single_definition] = STATE(24),
    [sym_syntactic_term] = STATE(14),
    [sym_syntactic_factor] = STATE(16),
    [sym_syntactic_primary] = STATE(15),
    [sym_optional_sequence] = STATE(13),
    [sym_repeated_sequence] = STATE(13),
    [sym_grouped_sequence] = STATE(13),
    [sym_special_sequence] = STATE(13),
    [sym_terminal_string] = STATE(13),
    [sym_comment] = STATE(2),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LPAREN_SLASH] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN_COLON] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_QMARK] = ACTIONS(21),
    [sym_empty_sequence] = ACTIONS(23),
    [sym_meta_identifier] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(29),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_definitions_list] = STATE(44),
    [sym_single_definition] = STATE(24),
    [sym_syntactic_term] = STATE(14),
    [sym_syntactic_factor] = STATE(16),
    [sym_syntactic_primary] = STATE(15),
    [sym_optional_sequence] = STATE(13),
    [sym_repeated_sequence] = STATE(13),
    [sym_grouped_sequence] = STATE(13),
    [sym_special_sequence] = STATE(13),
    [sym_terminal_string] = STATE(13),
    [sym_comment] = STATE(3),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LPAREN_SLASH] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN_COLON] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_QMARK] = ACTIONS(21),
    [sym_empty_sequence] = ACTIONS(23),
    [sym_meta_identifier] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(29),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_definitions_list] = STATE(43),
    [sym_single_definition] = STATE(24),
    [sym_syntactic_term] = STATE(14),
    [sym_syntactic_factor] = STATE(16),
    [sym_syntactic_primary] = STATE(15),
    [sym_optional_sequence] = STATE(13),
    [sym_repeated_sequence] = STATE(13),
    [sym_grouped_sequence] = STATE(13),
    [sym_special_sequence] = STATE(13),
    [sym_terminal_string] = STATE(13),
    [sym_comment] = STATE(4),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LPAREN_SLASH] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN_COLON] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_QMARK] = ACTIONS(21),
    [sym_empty_sequence] = ACTIONS(23),
    [sym_meta_identifier] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(29),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_definitions_list] = STATE(45),
    [sym_single_definition] = STATE(24),
    [sym_syntactic_term] = STATE(14),
    [sym_syntactic_factor] = STATE(16),
    [sym_syntactic_primary] = STATE(15),
    [sym_optional_sequence] = STATE(13),
    [sym_repeated_sequence] = STATE(13),
    [sym_grouped_sequence] = STATE(13),
    [sym_special_sequence] = STATE(13),
    [sym_terminal_string] = STATE(13),
    [sym_comment] = STATE(5),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LPAREN_SLASH] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN_COLON] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_QMARK] = ACTIONS(21),
    [sym_empty_sequence] = ACTIONS(23),
    [sym_meta_identifier] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(29),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_definitions_list] = STATE(47),
    [sym_single_definition] = STATE(24),
    [sym_syntactic_term] = STATE(14),
    [sym_syntactic_factor] = STATE(16),
    [sym_syntactic_primary] = STATE(15),
    [sym_optional_sequence] = STATE(13),
    [sym_repeated_sequence] = STATE(13),
    [sym_grouped_sequence] = STATE(13),
    [sym_special_sequence] = STATE(13),
    [sym_terminal_string] = STATE(13),
    [sym_comment] = STATE(6),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LPAREN_SLASH] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN_COLON] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_QMARK] = ACTIONS(21),
    [sym_empty_sequence] = ACTIONS(23),
    [sym_meta_identifier] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(29),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_definitions_list] = STATE(46),
    [sym_single_definition] = STATE(24),
    [sym_syntactic_term] = STATE(14),
    [sym_syntactic_factor] = STATE(16),
    [sym_syntactic_primary] = STATE(15),
    [sym_optional_sequence] = STATE(13),
    [sym_repeated_sequence] = STATE(13),
    [sym_grouped_sequence] = STATE(13),
    [sym_special_sequence] = STATE(13),
    [sym_terminal_string] = STATE(13),
    [sym_comment] = STATE(7),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LPAREN_SLASH] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN_COLON] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_QMARK] = ACTIONS(21),
    [sym_empty_sequence] = ACTIONS(23),
    [sym_meta_identifier] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(29),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LPAREN_SLASH,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN_COLON,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(8), 1,
      sym_comment,
    STATE(14), 1,
      sym_syntactic_term,
    STATE(15), 1,
      sym_syntactic_primary,
    STATE(16), 1,
      sym_syntactic_factor,
    STATE(29), 1,
      sym_single_definition,
    ACTIONS(23), 2,
      sym_empty_sequence,
      sym_meta_identifier,
    STATE(13), 5,
      sym_optional_sequence,
      sym_repeated_sequence,
      sym_grouped_sequence,
      sym_special_sequence,
      sym_terminal_string,
  [57] = 16,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LPAREN_SLASH,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN_COLON,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(9), 1,
      sym_comment,
    STATE(15), 1,
      sym_syntactic_primary,
    STATE(16), 1,
      sym_syntactic_factor,
    STATE(26), 1,
      sym_syntactic_term,
    ACTIONS(23), 2,
      sym_empty_sequence,
      sym_meta_identifier,
    STATE(13), 5,
      sym_optional_sequence,
      sym_repeated_sequence,
      sym_grouped_sequence,
      sym_special_sequence,
      sym_terminal_string,
  [111] = 15,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LPAREN_SLASH,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN_COLON,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(10), 1,
      sym_comment,
    STATE(15), 1,
      sym_syntactic_primary,
    STATE(28), 1,
      sym_syntactic_factor,
    ACTIONS(23), 2,
      sym_empty_sequence,
      sym_meta_identifier,
    STATE(13), 5,
      sym_optional_sequence,
      sym_repeated_sequence,
      sym_grouped_sequence,
      sym_special_sequence,
      sym_terminal_string,
  [162] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LPAREN_SLASH,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN_COLON,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    STATE(11), 1,
      sym_comment,
    STATE(21), 1,
      sym_syntactic_primary,
    ACTIONS(23), 2,
      sym_empty_sequence,
      sym_meta_identifier,
    STATE(13), 5,
      sym_optional_sequence,
      sym_repeated_sequence,
      sym_grouped_sequence,
      sym_special_sequence,
      sym_terminal_string,
  [207] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(12), 1,
      sym_comment,
    ACTIONS(31), 9,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [225] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(13), 1,
      sym_comment,
    ACTIONS(33), 9,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [243] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(37), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym_single_definition_repeat1,
    ACTIONS(35), 7,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [265] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(15), 1,
      sym_comment,
    ACTIONS(39), 9,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [283] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(43), 1,
      anon_sym_DASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(41), 8,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [303] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(37), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      sym_comment,
    STATE(23), 1,
      aux_sym_single_definition_repeat1,
    ACTIONS(45), 7,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [325] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(18), 1,
      sym_comment,
    ACTIONS(47), 9,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [343] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(19), 1,
      sym_comment,
    ACTIONS(49), 9,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [361] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(20), 1,
      sym_comment,
    ACTIONS(51), 9,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [379] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(21), 1,
      sym_comment,
    ACTIONS(53), 9,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [397] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(55), 9,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [415] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(59), 1,
      anon_sym_COMMA,
    STATE(23), 2,
      sym_comment,
      aux_sym_single_definition_repeat1,
    ACTIONS(57), 7,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [435] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(64), 1,
      anon_sym_PIPE,
    STATE(24), 1,
      sym_comment,
    STATE(25), 1,
      aux_sym_definitions_list_repeat1,
    ACTIONS(62), 6,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [456] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(64), 1,
      anon_sym_PIPE,
    STATE(25), 1,
      sym_comment,
    STATE(27), 1,
      aux_sym_definitions_list_repeat1,
    ACTIONS(66), 6,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [477] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(57), 8,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [494] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(70), 1,
      anon_sym_PIPE,
    STATE(27), 2,
      sym_comment,
      aux_sym_definitions_list_repeat1,
    ACTIONS(68), 6,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [513] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(28), 1,
      sym_comment,
    ACTIONS(73), 8,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [530] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(29), 1,
      sym_comment,
    ACTIONS(68), 7,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_SLASH_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON_RPAREN,
      anon_sym_RPAREN,
  [546] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(7), 1,
      sym_meta_identifier,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_comment,
    STATE(31), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_syntax_rule,
  [565] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      sym_meta_identifier,
    STATE(33), 1,
      sym_syntax_rule,
    STATE(31), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
  [582] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      sym_meta_identifier,
  [593] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym_meta_identifier,
  [604] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(86), 2,
      ts_builtin_sym_end,
      sym_meta_identifier,
  [615] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(88), 1,
      anon_sym_SQUOTE,
    STATE(35), 1,
      sym_comment,
  [625] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(90), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_comment,
  [635] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(92), 1,
      anon_sym_SEMI,
    STATE(37), 1,
      sym_comment,
  [645] = 3,
    ACTIONS(94), 1,
      aux_sym_special_sequence_token1,
    ACTIONS(96), 1,
      anon_sym_LPAREN_STAR,
    STATE(38), 1,
      sym_comment,
  [655] = 3,
    ACTIONS(96), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(98), 1,
      aux_sym_terminal_string_token2,
    STATE(39), 1,
      sym_comment,
  [665] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(100), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym_comment,
  [675] = 3,
    ACTIONS(96), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(102), 1,
      aux_sym_terminal_string_token1,
    STATE(41), 1,
      sym_comment,
  [685] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(104), 1,
      anon_sym_EQ,
    STATE(42), 1,
      sym_comment,
  [695] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(106), 1,
      anon_sym_SLASH_RPAREN,
    STATE(43), 1,
      sym_comment,
  [705] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(106), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      sym_comment,
  [715] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym_comment,
  [725] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_comment,
  [735] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(108), 1,
      anon_sym_COLON_RPAREN,
    STATE(47), 1,
      sym_comment,
  [745] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(112), 1,
      anon_sym_QMARK,
    STATE(48), 1,
      sym_comment,
  [755] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    STATE(49), 1,
      sym_comment,
  [765] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(88), 1,
      anon_sym_DQUOTE,
    STATE(50), 1,
      sym_comment,
  [775] = 3,
    ACTIONS(96), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(116), 1,
      aux_sym_comment_token1,
    STATE(51), 1,
      sym_comment,
  [785] = 1,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 57,
  [SMALL_STATE(10)] = 111,
  [SMALL_STATE(11)] = 162,
  [SMALL_STATE(12)] = 207,
  [SMALL_STATE(13)] = 225,
  [SMALL_STATE(14)] = 243,
  [SMALL_STATE(15)] = 265,
  [SMALL_STATE(16)] = 283,
  [SMALL_STATE(17)] = 303,
  [SMALL_STATE(18)] = 325,
  [SMALL_STATE(19)] = 343,
  [SMALL_STATE(20)] = 361,
  [SMALL_STATE(21)] = 379,
  [SMALL_STATE(22)] = 397,
  [SMALL_STATE(23)] = 415,
  [SMALL_STATE(24)] = 435,
  [SMALL_STATE(25)] = 456,
  [SMALL_STATE(26)] = 477,
  [SMALL_STATE(27)] = 494,
  [SMALL_STATE(28)] = 513,
  [SMALL_STATE(29)] = 530,
  [SMALL_STATE(30)] = 546,
  [SMALL_STATE(31)] = 565,
  [SMALL_STATE(32)] = 582,
  [SMALL_STATE(33)] = 593,
  [SMALL_STATE(34)] = 604,
  [SMALL_STATE(35)] = 615,
  [SMALL_STATE(36)] = 625,
  [SMALL_STATE(37)] = 635,
  [SMALL_STATE(38)] = 645,
  [SMALL_STATE(39)] = 655,
  [SMALL_STATE(40)] = 665,
  [SMALL_STATE(41)] = 675,
  [SMALL_STATE(42)] = 685,
  [SMALL_STATE(43)] = 695,
  [SMALL_STATE(44)] = 705,
  [SMALL_STATE(45)] = 715,
  [SMALL_STATE(46)] = 725,
  [SMALL_STATE(47)] = 735,
  [SMALL_STATE(48)] = 745,
  [SMALL_STATE(49)] = 755,
  [SMALL_STATE(50)] = 765,
  [SMALL_STATE(51)] = 775,
  [SMALL_STATE(52)] = 785,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional_sequence, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntactic_primary, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_definition, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntactic_factor, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntactic_term, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_definition, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_sequence, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repeated_sequence, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_sequence, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntactic_factor, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal_string, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_single_definition_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_single_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definitions_list, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definitions_list, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_definitions_list_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definitions_list_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntactic_term, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_rule, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_rule, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [114] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ebnf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
